#pragma once

#define CAMERA_SPEED		10

#define MAP_WIDTH			(TILESIZE*TILEX)
#define MAP_HEIGHT			(TILESIZE*TILEY)

#define DIR_L			0x01
#define DIR_R			0x02
#define DIR_U			0x04
#define DIR_D			0x08

#define COMMAND_MAX		9

enum FONTVERSION
{
	FONTVERSION_STARCRAFT,

	FONTVERSION_MAX
};

enum BRUSHVERSION
{
	BRUSHVERSION_WHITE,
	BRUSHVERSION_GRAY,

	BRUSHVERSION_MAX
};

enum COMMNADTYPE
{
	COMMNADTYPE_MOVE,
	COMMNADTYPE_STOP,
	COMMNADTYPE_ATTACK,
	COMMNADTYPE_PATROL,
	COMMNADTYPE_HOLD,


};

enum COMMANDSET
{
	COMMANDSET_COMMON,
	COMMANDSET_WORKER,
	//ZERG
	COMMANDSET_ZERGATTACK1,
	COMMANDSET_LARVA,
	COMMANDSET_ZERGEGG,
	COMMANDSET_DRONE,
	COMMANDSET_HYDRALISK,
	COMMANDSET_LURKER,
	COMMANDSET_QUEEN,
	COMMANDSET_MUTALISK,

};

enum DIRECTION
{
	DIRECTION_NONE = 0,
	DIRECTION_LF = DIR_L,
	DIRECTION_RG = DIR_R,
	DIRECTION_UP = DIR_U,
	DIRECTION_DN = DIR_D,
	DIRECTION_LU = DIR_L | DIR_U,
	DIRECTION_RU = DIR_R | DIR_U,
	DIRECTION_LD = DIR_L | DIR_D,
	DIRECTION_RD = DIR_R | DIR_D,
};

enum PLAYER
{
	PLAYER_NONE = -1,
	PLAYER1,
	//PLAYER2,

	PLAYER_NUM
};

enum RACES
{
	TERRAN,
	PROTOSS,
	ZERG,

	RACES_NUM
};

enum UNITSIZE
{
	UNITSIZE_SMALL,
	UNITSIZE_MEDIUM,
	UNITSIZE_LARGE
};

enum DAMAGETYPE
{
	DAMAGETYPE_NORMAL,		//일반공격
	DAMAGETYPE_CONCUSSIVE,	//진동형
	DAMAGETYPE_EXPLOSIVE	//폭발형
};

enum UNITNUM_ZERG
{
	//GROUND
	UNITNUM_ZERG_NONE = -1,
	UNITNUM_ZERG_LARVA,
	UNITNUM_ZERG_ZERGEGG,
	UNITNUM_ZERG_DRONE,
	UNITNUM_ZERG_ZERGLING,
	UNITNUM_ZERG_HYDRALISK,
	UNITNUM_ZERG_LURKER,
	UNITNUM_ZERG_LURKEREGG,
	UNITNUM_ZERG_ULTRALISK,
	UNITNUM_ZERG_BROODLING,
	UNITNUM_ZERG_DEFILER,
	UNITNUM_ZERG_INFESTEDTERRAN,

	//AIR
	UNITNUM_ZERG_OVERLORD,
	UNITNUM_ZERG_MUTALISK,
	UNITNUM_ZERG_SCOURGE,
	UNITNUM_ZERG_QUEEN,
	UNITNUM_ZERG_COCOON,
	UNITNUM_ZERG_GUADIAN,
	UNITNUM_ZERG_DEVOURER,
};

enum UNITNUM_TERRAN
{
	//GROUND
	UNITNUM_TERRAN_NONE = -1,
	UNITNUM_TERRAN_SCV,
	UNITNUM_TERRAN_MARINE,
	UNITNUM_TERRAN_FIREBAT,
	UNITNUM_TERRAN_MEDIC,
	UNITNUM_TERRAN_GHOST,
	UNITNUM_TERRAN_VULTURE,
	UNITNUM_TERRAN_SPIDERMINE,
	UNITNUM_TERRAN_SIEGETANK_TANKMODE,
	UNITNUM_TERRAN_SIEGETANK_SIEGEMODE,
	UNITNUM_TERRAN_GOLIATH,

	//AIR
	UNITNUM_TERRAN_WRAITH,
	UNITNUM_TERRAN_DROPSHIP,
	UNITNUM_TERRAN_SCIENCEVESSEL,
	UNITNUM_TERRAN_VALKYRIE,
	UNITNUM_TERRAN_BATTLECRUISER,
};

enum UNITNUM_PROTOSS
{
	//GROUND
	UNITNUM_PROTOSS_NONE = -1,
	UNITNUM_PROTOSS_PROBE,
	UNITNUM_PROTOSS_ZEALOT,
	UNITNUM_PROTOSS_DRAGOON,
	UNITNUM_PROTOSS_HIGHTEMPLAR,
	UNITNUM_PROTOSS_ARCHON,
	UNITNUM_PROTOSS_DARKTEMPLAR,
	UNITNUM_PROTOSS_DARKARCHON,
	UNITNUM_PROTOSS_REAVER,
	UNITNUM_PROTOSS_SCARAB,


	//AIR
	UNITNUM_PROTOSS_SHUTTLE,
	UNITNUM_PROTOSS_OBSERVER,
	UNITNUM_PROTOSS_SCOUT,
	UNITNUM_PROTOSS_CORSAIR,
	UNITNUM_PROTOSS_ARBITER,
	UNITNUM_PROTOSS_CARRIER,
	UNITNUM_PROTOSS_INTERCEPTOR,
};
