#pragma once


//UNIT SIZE
#define UNITSIZE_ZERG_LARVA				{ 26, 26 }
#define UNITSIZE_ZERG_ZERGEGG			{ 30, 30 }
#define UNITSIZE_ZERG_DRONE				{ 36, 32 }
#define UNITSIZE_ZERG_ZERGLING			{ 16, 16 }
#define UNITSIZE_ZERG_HYDRALISK			{ 21, 23 }
#define UNITSIZE_ZERG_LURKER			{ 32, 32 }
//#define UNITSIZE_ZERG_LURKEREGG
#define UNITSIZE_ZERG_ULTRALISK			{ 38, 32 }
#define UNITSIZE_ZERG_BROODLING			{ 19, 19 }
#define UNITSIZE_ZERG_DEFILER			{ 27, 25 }
#define UNITSIZE_ZERG_INFESTEDTERRAN	{ 17, 20 }
#define UNITSIZE_ZERG_OVERLORD			{ 50, 50 }
#define UNITSIZE_ZERG_MUTALISK			{ 44, 44 }
#define UNITSIZE_ZERG_SCOURGE			{ 24, 24 }
#define UNITSIZE_ZERG_QUEEN				{ 48, 48 }
//#define UNITSIZE_ZERG_COCOON
#define UNITSIZE_ZERG_GUADIAN			{ 44, 44 }
#define UNITSIZE_ZERG_DEVOURER			{ 44, 44 }


//BUILD SIZE
#define BUILDSIZE_HATCHERY				{ 4, 3 }
#define BUILDSIZE_LAIR					{ 4, 3 }
#define BUILDSIZE_HIVE					{ 4, 3 }
#define BUILDSIZE_CREEPCOLONY			{ 2, 2 }
#define BUILDSIZE_SUNKENCOLONY			{ 2, 2 }
#define BUILDSIZE_SPORECOLONY			{ 2, 2 }
#define BUILDSIZE_EXTRACTOR				{ 4, 2 }
#define BUILDSIZE_SPAWNINGPOOL			{ 3, 2 }
#define BUILDSIZE_EVOLUTIONCHAMBER		{ 3, 2 }
#define BUILDSIZE_HYDRALISKDEN			{ 3, 2 }
#define BUILDSIZE_SPIRE					{ 2, 2 }
#define BUILDSIZE_GREATERSPIRE			{ 2, 2 }
#define BUILDSIZE_QUEENSNEST			{ 3, 2 }
#define BUILDSIZE_NYDUSCANAL			{ 2, 2 }
#define BUILDSIZE_ULTRALISKCAVERN		{ 3, 2 }
#define BUILDSIZE_DEFILERMOUND			{ 4, 2 }



//BUILD COST
#define BUILDCOST_HATCHERY				{ 300,   0 }
#define BUILDCOST_LAIR					{ 150, 100 }
#define BUILDCOST_HIVE					{ 200, 150 }
#define BUILDCOST_CREEPCOLONY			{  75,   0 }
#define BUILDCOST_SUNKENCOLONY			{  50,   0 }
#define BUILDCOST_SPORECOLONY			{  50,   0 }
#define BUILDCOST_EXTRACTOR				{  50,   0 }
#define BUILDCOST_SPAWNINGPOOL			{ 200,   0 }
#define BUILDCOST_EVOLUTIONCHAMBER		{  75,   0 }
#define BUILDCOST_HYDRALISKDEN			{ 100,  50 }
#define BUILDCOST_SPIRE					{ 200, 150 }
#define BUILDCOST_GREATERSPIRE			{ 100, 150 }
#define BUILDCOST_QUEENSNEST			{ 150, 100 }
#define BUILDCOST_NYDUSCANAL			{ 150,   0 }
#define BUILDCOST_ULTRALISKCAVERN		{ 150, 200 }
#define BUILDCOST_DEFILERMOUND			{ 100, 100 }


